### ISSUE TITLE
Bug: Legend Studio 4.8.0 hangs and eventually times out when any authenticated page is accessed

### ISSUE THREAD

**Issue by epsstan** [finos/legend-studio#1073]
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Studio

### Current and expected behavior

Actual : Accessing the home page (or any authenticated page) results in a HTTP timeout.
Expected : Studio should redirect to the Gitlab OAuth consent page

### Steps to reproduce

- Checkout and build Studio 4.8.0
- Checkout and build legend-shared 0.20.0
- Add the Studio static assets dir (dist/studio) to the classpath of the legend-shared-server module
- Run a local instance of mongo with user/password set to 'admin'
- Run org.finos.legend.server.shared.staticserver.Server with the dummy config.json below
- Once the server has initialized, access http://localhost:8080 in a browser. You should see no response 
- The server console shows a Java method notfound error 

```
DEBUG [2022-04-15 05:10:23,433] org.pac4j.oidc.redirect.OidcRedirectActionBuilder: Authentication request url: https://gitlab.com/oauth/authorize?response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fstudio%2Flog.in%2Fcallback%3Fclient_name%3Dgitlab&state=UHmDPMpfPtmCh3K3vkgJcmXPVRCzgOkBn0SBXxZT8es&client_id=XXXXXX&scope=openid+profile+api
WARN  [2022-04-15 05:10:23,437] org.eclipse.jetty.server.HttpChannel: /
! java.lang.NoSuchMethodError: 'org.eclipse.jetty.util.Callback org.eclipse.jetty.util.Callback.from(org.eclipse.jetty.util.thread.Invocable$InvocationType, java.lang.Runnable, java.util.function.Consumer)'
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:550)
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
! at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
! at java.base/java.lang.Thread.run(Thread.java:829)
WARN  [2022-04-15 05:10:23,437] org.eclipse.jetty.server.HttpChannelState: unhandled in state COMPLETING
! java.lang.NoSuchMethodError: 'org.eclipse.jetty.util.Callback org.eclipse.jetty.util.Callback.from(org.eclipse.jetty.util.thread.Invocable$InvocationType, java.lang.Runnable, java.util.function.Consumer)'
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:550)
! ... 7 common frames omitted
! Causing: java.lang.IllegalStateException: java.lang.NoSuchMethodError: 'org.eclipse.jetty.util.Callback org.eclipse.jetty.util.Callback.from(org.eclipse.jetty.util.thread.Invocable$InvocationType, java.lang.Runnable, java.util.function.Consumer)'
! at org.eclipse.jetty.server.HttpChannelState.onError(HttpChannelState.java:813)
! at org.eclipse.jetty.server.HttpChannel.handleException(HttpChannel.java:695)
! at org.eclipse.jetty.server.HttpChannelOverHttp.handleException(HttpChannelOverHttp.java:488)
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:564)
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
! at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
! at java.base/java.lang.Thread.run(Thread.java:829)
```

```json
{
  "pac4j": {
    "callbackPrefix": "/studio/log.in",
    "bypassPaths": ["/studio/admin/healthcheck"],
    "mongoUri": "mongodb://admin:admin@172.18.224.1:27017",
    "mongoDb": "legend",
    "clients": [
      {
        "org.finos.legend.server.pac4j.gitlab.GitlabClient": {
          "name" : "gitlab",
          "clientId" : "XXXX",
          "secret": "YYYY",
          "discoveryUri": "https://gitlab.com/.well-known/openid-configuration",
          "scope": "openid profile api"
        }
      }
    ],
    "mongoSession": {
      "enabled": true,
      "collection": "userSessions"
    }
  },
  "html5Router": true,
  "routerExemptPaths": [
    "/editor.worker.js",
    "/json.worker.js",
    "/editor.worker.js.map",
    "/json.worker.js.map",
    "/version.json",
    "/config.json",
    "/favicon.ico",
    "/static"
  ],
  "localAssetPaths": {
    "/studio/config.json" : "/config/uiConfig.json"
  },
  "uiPath": "/studio",
  "server": {
    "type": "simple",
    "applicationContextPath": "/",
    "adminContextPath": "/studio/admin",
    "connector": {
      "type": "http",
      "port": 8080
    }
  },
  "logging": {
    "level": "INFO",
    "loggers" : {
      "root": { "level": "info"},
      "org.pac4j": { "level": "debug"}
    },
    "appenders": [
      {
        "type": "console"
      }
    ]
  }
}
```

### Environment

```text
System: 
 OS : Windows
```

### Possible solution and workaround

Problem :
1/ When an authenticated page is accessed and the user has not already been authenticated,  the Server initiates the Pac4j authentication protocol 
2/ In this protocol, it attempts to redirect the user to the Gitlab consent page. When doing so, the Server encounters a method not found error. Concretely the Jetty server HttpChannel class is looking for Jetty client Callback.from(p1,p2,p3) method  and this method is not found. The method not found error is not gracefully handled and response is not sent back to the browser.

There is mismatch between the Jetty server and client versions. 

dropwizard-logging brings in Jetty client org.eclipse.jetty:jetty-util:jar:9.4.35.v20201120:compile
dropwizard-server brings in org.eclipse.jetty:jetty-server:jar:9.4.44.v20210927:compile

server 9.4.44 and 9.4.35 are not compatible with each other.

Solution : 
Solution is to use compatible server + client versions.  See below for a crude patch. 
With this patch, the method not found error is avoided and the server sends a redirect response to the browser.

```patch
Index: legend-shared-server/pom.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/legend-shared-server/pom.xml b/legend-shared-server/pom.xml
--- a/legend-shared-server/pom.xml	(revision ac5948474bdee30afb6be6fdf1c90a96220cf4da)
+++ b/legend-shared-server/pom.xml	(date 1649999863713)
@@ -31,6 +31,10 @@
     <build>
         <plugins>
             <plugin>
+                <groupId>org.apache.maven.plugins</groupId>
+                <artifactId>maven-dependency-plugin</artifactId>
+            </plugin>
+            <plugin>
                 <artifactId>maven-shade-plugin</artifactId>
                 <configuration>
                     <filters>
@@ -129,6 +133,13 @@
         </dependency>
         <!-- JAXB -->
 
+        <!-- Jetty -->
+        <dependency>
+            <groupId>org.eclipse.jetty</groupId>
+            <artifactId>jetty-util</artifactId>
+            <version>9.4.44.v20210927</version>
+        </dependency>
+
         <!-- TEST -->
         <dependency>
             <groupId>junit</groupId>
Index: pom.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/pom.xml b/pom.xml
--- a/pom.xml	(revision ac5948474bdee30afb6be6fdf1c90a96220cf4da)
+++ b/pom.xml	(date 1649999863713)
@@ -519,6 +519,12 @@
                 <groupId>io.dropwizard</groupId>
                 <artifactId>dropwizard-core</artifactId>
                 <version>${dropwizard.version}</version>
+                <exclusions>
+                    <exclusion>
+                        <groupId>org.eclipse.jetty</groupId>
+                        <artifactId>jetty-util</artifactId>
+                    </exclusion>
+                </exclusions>
             </dependency>
             <dependency>
                 <groupId>io.dropwizard</groupId>
Index: legend-shared-pac4j/pom.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/legend-shared-pac4j/pom.xml b/legend-shared-pac4j/pom.xml
--- a/legend-shared-pac4j/pom.xml	(revision ac5948474bdee30afb6be6fdf1c90a96220cf4da)
+++ b/legend-shared-pac4j/pom.xml	(date 1649999863713)
@@ -89,5 +89,10 @@
             <scope>test</scope>
         </dependency>
         <!-- TEST -->
+        <dependency>
+            <groupId>org.eclipse.jetty</groupId>
+            <artifactId>jetty-util</artifactId>
+            <version>9.4.44.v20210927</version>
+        </dependency>
     </dependencies>
 </project>
```

### Contribution

- [ ] I would like to work on the fix for this issue

**Comment by akphi** [comment]
thank you @epsstan for debugging this and fixing this in https://github.com/finos/legend-shared/pull/145
We have tried to deploy this to https://legend-acct.finos.org/studio and we seem to be in shape now 🎉
